;;; standard-themes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from standard-dark-theme.el

(register-definition-prefixes "standard-dark-theme" '("standard-dark-palette"))


;;; Generated autoloads from standard-dark-tinted-theme.el

(register-definition-prefixes "standard-dark-tinted-theme" '("standard-dark-tinted-palette"))


;;; Generated autoloads from standard-light-theme.el

(register-definition-prefixes "standard-light-theme" '("standard-light-palette"))


;;; Generated autoloads from standard-light-tinted-theme.el

(register-definition-prefixes "standard-light-tinted-theme" '("standard-light-tinted-palette"))


;;; Generated autoloads from standard-themes.el

(defvar standard-themes-take-over-modus-themes-mode nil "\
Non-nil if Standard-Themes-Take-Over-Modus-Themes mode is enabled.
See the `standard-themes-take-over-modus-themes-mode' command
for a description of this minor mode.")
(custom-autoload 'standard-themes-take-over-modus-themes-mode "standard-themes" nil)
(autoload 'standard-themes-take-over-modus-themes-mode "standard-themes" "\
When enabled, all Modus themes commands consider only Standard themes.

Alternatively, use the commands `standard-themes-rotate',
`standard-themes-select', `standard-themes-load-random',
`standard-themes-load-random-dark', `standard-themes-load-random-light',
`standard-themes-list-colors', `standard-themes-list-colors-current'.
They are all designed to only consider Standard themes.

This is a global minor mode.  If called interactively, toggle the
`Standard-Themes-Take-Over-Modus-Themes mode' mode.  If the prefix
argument is positive, enable the mode, and if it is zero or negative,
disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value
\\='standard-themes-take-over-modus-themes-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
 (autoload 'standard-themes-toggle "standard-themes")
 (autoload 'standard-themes-rotate "standard-themes")
 (autoload 'standard-themes-select "standard-themes")
 (autoload 'standard-themes-load-random "standard-themes")
 (autoload 'standard-themes-load-random-dark "standard-themes")
 (autoload 'standard-themes-load-random-light "standard-themes")
 (autoload 'standard-themes-list-colors "standard-themes")
 (autoload 'standard-themes-list-colors-current "standard-themes")
(when load-file-name (let ((dir (file-name-directory load-file-name))) (unless (file-equal-p dir (expand-file-name "themes/" data-directory)) (add-to-list 'custom-theme-load-path dir))))
(register-definition-prefixes "standard-themes" '("standard-themes-"))

;;; End of scraped data

(provide 'standard-themes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; standard-themes-autoloads.el ends here
