;;; evil-collection-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from evil-collection.el

(autoload 'evil-collection-translate-minor-mode-key "evil-collection" "\
Translate keys in the keymap(s) corresponding to STATES and MODES.

Similar to `evil-collection-translate-key' but for minor modes.
STATES should be the name of an evil state, a list of states, or nil. MODES
should be a symbol corresponding to minor-mode to make the translations in or a
list of minor-mode symbols. TRANSLATIONS corresponds to a list of
key replacement pairs. For example, specifying \"a\" \"b\" will bind \"a\" to
\"b\"'s definition in the keymap. Specifying nil as a replacement will unbind a
key. If DESTRUCTIVE is nil, a backup of the keymap will be stored on the initial
invocation, and future invocations will always look up keys in the backup
keymap. When no TRANSLATIONS are given, this function will only create the
backup keymap without making any translations. On the other hand, if DESTRUCTIVE
is non-nil, the keymap will be destructively altered without creating a backup.
For example, calling this function multiple times with \"a\" \"b\" \"b\" \"a\"
would continue to swap and unswap the definitions of these keys. This means that
when DESTRUCTIVE is non-nil, all related swaps/cycles should be done in the same
invocation.

(fn STATES MODES &rest TRANSLATIONS &key DESTRUCTIVE &allow-other-keys)")
(function-put 'evil-collection-translate-minor-mode-key 'lisp-indent-function 'defun)
(autoload 'evil-collection-translate-key "evil-collection" "\
Translate keys in the keymap(s) corresponding to STATES and KEYMAPS.
STATES should be the name of an evil state, a list of states, or nil. KEYMAPS
should be a symbol corresponding to the keymap to make the translations in or a
list of keymap symbols. Like `evil-define-key', when a keymap does not exist,
the keybindings will be deferred until the keymap is defined, so
`with-eval-after-load' is not necessary. TRANSLATIONS corresponds to a list of
key replacement pairs. For example, specifying \"a\" \"b\" will bind \"a\" to
\"b\"'s definition in the keymap. Specifying nil as a replacement will unbind a
key. If DESTRUCTIVE is nil, a backup of the keymap will be stored on the initial
invocation, and future invocations will always look up keys in the backup
keymap. When no TRANSLATIONS are given, this function will only create the
backup keymap without making any translations. On the other hand, if DESTRUCTIVE
is non-nil, the keymap will be destructively altered without creating a backup.
For example, calling this function multiple times with \"a\" \"b\" \"b\" \"a\"
would continue to swap and unswap the definitions of these keys. This means that
when DESTRUCTIVE is non-nil, all related swaps/cycles should be done in the same
invocation.

(fn STATES KEYMAPS &rest TRANSLATIONS &key DESTRUCTIVE &allow-other-keys)")
(function-put 'evil-collection-translate-key 'lisp-indent-function 'defun)
(autoload 'evil-collection-swap-key "evil-collection" "\
Wrapper around `evil-collection-translate-key' for swapping keys.
STATES, KEYMAPS, and ARGS are passed to `evil-collection-translate-key'. ARGS
should consist of key swaps (e.g. \"a\" \"b\" is equivalent to \"a\" \"b\" \"b\"
\"a\" with `evil-collection-translate-key') and optionally keyword arguments for
`evil-collection-translate-key'.

(fn STATES KEYMAPS &rest ARGS)" nil t)
(function-put 'evil-collection-swap-key 'lisp-indent-function 'defun)
(autoload 'evil-collection-swap-minor-mode-key "evil-collection" "\
Wrapper around `evil-collection-translate-minor-mode-key' for swapping keys.
STATES, MODES, and ARGS are passed to
`evil-collection-translate-minor-mode-key'. ARGS should consist of key swaps
(e.g. \"a\" \"b\" is equivalent to \"a\" \"b\" \"b\" \"a\"
with `evil-collection-translate-minor-mode-key') and optionally keyword
arguments for `evil-collection-translate-minor-mode-key'.

(fn STATES MODES &rest ARGS)" nil t)
(function-put 'evil-collection-swap-minor-mode-key 'lisp-indent-function 'defun)
(autoload 'evil-collection-require "evil-collection" "\
Require the evil-collection-MODE file, but do not activate it.

MODE should be a symbol. This requires the evil-collection-MODE
feature without needing to manipulate `load-path'. NOERROR is
forwarded to `require'.

(fn MODE &optional NOERROR)")
(autoload 'evil-collection-init "evil-collection" "\
Register the Evil bindings for all modes in `evil-collection-mode-list'.

Alternatively, you may register select bindings manually, for
instance:

  (with-eval-after-load ='calendar
    (evil-collection-calendar-setup))

If MODES is specified (as either one mode or a list of modes), use those modes
instead of the modes in `evil-collection-mode-list'.

(fn &optional MODES)" t)
(register-definition-prefixes "evil-collection" '("evil-collection-"))


;;; Generated autoloads from modes/2048-game/evil-collection-2048-game.el

(autoload 'evil-collection-2048-game-setup "modes/2048-game/evil-collection-2048-game" "\
Set up `evil' bindings for `2048-game'.")
(register-definition-prefixes "modes/2048-game/evil-collection-2048-game" '("evil-collection-2048-game-maps"))


;;; Generated autoloads from modes/ag/evil-collection-ag.el

(autoload 'evil-collection-ag-setup "modes/ag/evil-collection-ag" "\
Set up `evil' bindings for `ag'.")
(register-definition-prefixes "modes/ag/evil-collection-ag" '("evil-collection-ag-maps"))


;;; Generated autoloads from modes/alchemist/evil-collection-alchemist.el

(autoload 'evil-collection-alchemist-setup "modes/alchemist/evil-collection-alchemist" "\
Set up `evil' bindings for `alchemist'.")
(register-definition-prefixes "modes/alchemist/evil-collection-alchemist" '("evil-collection-alchemist-maps"))


;;; Generated autoloads from modes/anaconda-mode/evil-collection-anaconda-mode.el

(autoload 'evil-collection-anaconda-mode-setup "modes/anaconda-mode/evil-collection-anaconda-mode" "\
Set up `evil' bindings for `anaconda-mode'.")
(register-definition-prefixes "modes/anaconda-mode/evil-collection-anaconda-mode" '("evil-collection-anaconda-mode-maps"))


;;; Generated autoloads from modes/apropos/evil-collection-apropos.el

(autoload 'evil-collection-apropos-setup "modes/apropos/evil-collection-apropos" "\
Set up `evil' bindings for `apropos'.")
(register-definition-prefixes "modes/apropos/evil-collection-apropos" '("evil-collection-apropos-maps"))


;;; Generated autoloads from modes/arc-mode/evil-collection-arc-mode.el

(autoload 'evil-collection-arc-mode-setup "modes/arc-mode/evil-collection-arc-mode" "\
Set up `evil' bindings for `arc-mode'.")
(register-definition-prefixes "modes/arc-mode/evil-collection-arc-mode" '("evil-collection-arc-mode-maps"))


;;; Generated autoloads from modes/atomic-chrome/evil-collection-atomic-chrome.el

(autoload 'evil-collection-atomic-chrome-setup "modes/atomic-chrome/evil-collection-atomic-chrome" "\
Set up `evil' bindings for `atomic-chrome'.")
(register-definition-prefixes "modes/atomic-chrome/evil-collection-atomic-chrome" '("evil-collection-atomic-chrome-maps"))


;;; Generated autoloads from modes/auto-package-update/evil-collection-auto-package-update.el

(autoload 'evil-collection-auto-package-update-setup "modes/auto-package-update/evil-collection-auto-package-update" "\
Set up `evil' bindings for `auto-package-update'.")
(register-definition-prefixes "modes/auto-package-update/evil-collection-auto-package-update" '("evil-collection-auto-package-update-maps"))


;;; Generated autoloads from modes/beginend/evil-collection-beginend.el

(autoload 'evil-collection-beginend-setup "modes/beginend/evil-collection-beginend" "\
Set up `evil' bindings for `beginend'.")
(register-definition-prefixes "modes/beginend/evil-collection-beginend" '("evil-beginend--define-"))


;;; Generated autoloads from modes/bluetooth/evil-collection-bluetooth.el

(autoload 'evil-collection-bluetooth-setup "modes/bluetooth/evil-collection-bluetooth" "\
Set up `evil' bindings for `bluetooth'.")
(register-definition-prefixes "modes/bluetooth/evil-collection-bluetooth" '("evil-collection-bluetooth-maps"))


;;; Generated autoloads from modes/bm/evil-collection-bm.el

(autoload 'evil-collection-bm-setup "modes/bm/evil-collection-bm" "\
Set up `evil' bindings for `bm'.")
(register-definition-prefixes "modes/bm/evil-collection-bm" '("evil-collection-bm-maps"))


;;; Generated autoloads from modes/bookmark/evil-collection-bookmark.el

(autoload 'evil-collection-bookmark-setup "modes/bookmark/evil-collection-bookmark" "\
Set up `evil' bindings for `bookmark'.")
(register-definition-prefixes "modes/bookmark/evil-collection-bookmark" '("evil-collection-bookmark-maps"))


;;; Generated autoloads from modes/buff-menu/evil-collection-buff-menu.el

(autoload 'evil-collection-buff-menu-setup "modes/buff-menu/evil-collection-buff-menu" "\
Set up `evil' bindings for `buff-menu'..")
(register-definition-prefixes "modes/buff-menu/evil-collection-buff-menu" '("evil-collection-buff-menu-"))


;;; Generated autoloads from modes/bufler/evil-collection-bufler.el

(autoload 'evil-collection-bufler-setup "modes/bufler/evil-collection-bufler" "\
Set up `evil' bindings for `bufler'.")
(register-definition-prefixes "modes/bufler/evil-collection-bufler" '("evil-collection-bufler-m"))


;;; Generated autoloads from modes/calc/evil-collection-calc.el

(autoload 'evil-collection-calc-setup "modes/calc/evil-collection-calc" "\
Set up `evil' bindings for `calc'.")
(register-definition-prefixes "modes/calc/evil-collection-calc" '("evil-collection-calc-maps"))


;;; Generated autoloads from modes/calendar/evil-collection-calendar.el

(autoload 'evil-collection-calendar-setup "modes/calendar/evil-collection-calendar" "\
Set up `evil' bindings for `calendar'.")
(register-definition-prefixes "modes/calendar/evil-collection-calendar" '("evil-collection-calendar-"))


;;; Generated autoloads from modes/cider/evil-collection-cider.el

(autoload 'evil-collection-cider-setup "modes/cider/evil-collection-cider" "\
Set up `evil' bindings for `cider'.")
(register-definition-prefixes "modes/cider/evil-collection-cider" '("evil-collection-cider-"))


;;; Generated autoloads from modes/citre/evil-collection-citre.el

(autoload 'evil-collection-citre-setup "modes/citre/evil-collection-citre" "\
Set up `evil' bindings for `citre'.")
(register-definition-prefixes "modes/citre/evil-collection-citre" '("evil-collection-citre-set-bindings"))


;;; Generated autoloads from modes/cmake-mode/evil-collection-cmake-mode.el

(autoload 'evil-collection-cmake-mode-setup "modes/cmake-mode/evil-collection-cmake-mode" "\
Set up `evil' bindings for `cmake-mode'.")
(register-definition-prefixes "modes/cmake-mode/evil-collection-cmake-mode" '("evil-collection-cmake-mode-set-evil-shift-width"))


;;; Generated autoloads from modes/color-rg/evil-collection-color-rg.el

(autoload 'evil-collection-color-rg-setup "modes/color-rg/evil-collection-color-rg" "\
Set up `evil' bindings for color-rg.")
(register-definition-prefixes "modes/color-rg/evil-collection-color-rg" '("evil-collection-color-rg-maps"))


;;; Generated autoloads from modes/comint/evil-collection-comint.el

(autoload 'evil-collection-comint-setup "modes/comint/evil-collection-comint" "\
Set up `evil' bindings for `comint'.")
(register-definition-prefixes "modes/comint/evil-collection-comint" '("evil-collection-comint-maps"))


;;; Generated autoloads from modes/company/evil-collection-company.el

(autoload 'evil-collection-company-whole-lines "modes/company/evil-collection-company" "\
`company-mode' completion backend that completes whole-lines, akin to vim's
C-x C-l.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(autoload 'evil-collection-company-setup "modes/company/evil-collection-company" "\
Set up `evil' bindings for `company'.")
(register-definition-prefixes "modes/company/evil-collection-company" '("evil-collection-"))


;;; Generated autoloads from modes/compile/evil-collection-compile.el

(autoload 'evil-collection-compile-setup "modes/compile/evil-collection-compile" "\
Set up `evil' bindings for `compile'.")
(register-definition-prefixes "modes/compile/evil-collection-compile" '("evil-collection-compile-maps"))


;;; Generated autoloads from modes/consult/evil-collection-consult.el

(autoload 'evil-collection-consult-mark "modes/consult/evil-collection-consult" "\
Jump to an evil marker in the current buffer." t)
(autoload 'evil-collection-consult-jump-list "modes/consult/evil-collection-consult" "\
Jump to a position in the evil jump list." t)
(autoload 'evil-collection-consult-setup "modes/consult/evil-collection-consult" "\
Set up `evil' bindings for `consult'.")
(register-definition-prefixes "modes/consult/evil-collection-consult" '("evil-collection-consult-"))


;;; Generated autoloads from modes/corfu/evil-collection-corfu.el

(autoload 'evil-collection-corfu-setup "modes/corfu/evil-collection-corfu" "\
Set up `evil' bindings for `corfu'.")
(register-definition-prefixes "modes/corfu/evil-collection-corfu" '("evil-collection-corfu-"))


;;; Generated autoloads from modes/crdt/evil-collection-crdt.el

(register-definition-prefixes "modes/crdt/evil-collection-crdt" '("evil-collection-crdt-"))


;;; Generated autoloads from modes/csv/evil-collection-csv.el

(autoload 'evil-collection-csv-setup "modes/csv/evil-collection-csv" "\
Set up `evil' bindings for csv.")
(register-definition-prefixes "modes/csv/evil-collection-csv" '("evil-collection-csv-maps"))


;;; Generated autoloads from modes/cus-theme/evil-collection-cus-theme.el

(autoload 'evil-collection-cus-theme-setup "modes/cus-theme/evil-collection-cus-theme" "\
Set up `evil' bindings for `cus-theme'.")
(register-definition-prefixes "modes/cus-theme/evil-collection-cus-theme" '("evil-collection-cus-theme-maps"))


;;; Generated autoloads from modes/custom/evil-collection-custom.el

(autoload 'evil-collection-custom-setup "modes/custom/evil-collection-custom" "\
Set up `evil' bindings for `Custom-mode'.")
(register-definition-prefixes "modes/custom/evil-collection-custom" '("evil-collection-custom-maps"))


;;; Generated autoloads from modes/daemons/evil-collection-daemons.el

(autoload 'evil-collection-daemons-setup "modes/daemons/evil-collection-daemons" "\
Set up `evil' bindings for `daemons'.")
(register-definition-prefixes "modes/daemons/evil-collection-daemons" '("evil-collection-daemons-maps"))


;;; Generated autoloads from modes/dape/evil-collection-dape.el

(autoload 'evil-collection-dape-setup "modes/dape/evil-collection-dape" "\
Set up `evil' bindings for `dape'.")
(register-definition-prefixes "modes/dape/evil-collection-dape" '("evil-collection-dape-"))


;;; Generated autoloads from modes/dashboard/evil-collection-dashboard.el

(autoload 'evil-collection-dashboard-setup "modes/dashboard/evil-collection-dashboard" "\
Set up Evil bindings for Dashboard.")
(register-definition-prefixes "modes/dashboard/evil-collection-dashboard" '("evil-collection-dashboard-"))


;;; Generated autoloads from modes/deadgrep/evil-collection-deadgrep.el

(autoload 'evil-collection-deadgrep-setup "modes/deadgrep/evil-collection-deadgrep" "\
Set up `evil' bindings for deadgrep..")
(register-definition-prefixes "modes/deadgrep/evil-collection-deadgrep" '("evil-collection-deadgrep-maps"))


;;; Generated autoloads from modes/debbugs/evil-collection-debbugs.el

(autoload 'evil-collection-debbugs-setup "modes/debbugs/evil-collection-debbugs" "\
Set up `evil' bindings for `debbugs-gnu-mode'.")
(register-definition-prefixes "modes/debbugs/evil-collection-debbugs" '("evil-collection-debbugs-maps"))


;;; Generated autoloads from modes/debug/evil-collection-debug.el

(autoload 'evil-collection-debug-setup "modes/debug/evil-collection-debug" "\
Set up `evil' bindings for `debug'.")
(register-definition-prefixes "modes/debug/evil-collection-debug" '("evil-collection-debug-maps"))


;;; Generated autoloads from modes/devdocs/evil-collection-devdocs.el

(autoload 'evil-collection-devdocs-setup "modes/devdocs/evil-collection-devdocs" "\
Set up `evil' bindings for `devdocs'.")
(register-definition-prefixes "modes/devdocs/evil-collection-devdocs" '("evil-collection-devdocs-maps"))


;;; Generated autoloads from modes/dictionary/evil-collection-dictionary.el

(autoload 'evil-collection-dictionary-setup "modes/dictionary/evil-collection-dictionary" "\
Set up `evil' bindings for `dictionary'.")
(register-definition-prefixes "modes/dictionary/evil-collection-dictionary" '("evil-collection-dictionary-maps"))


;;; Generated autoloads from modes/diff-hl/evil-collection-diff-hl.el

(autoload 'evil-collection-diff-hl-setup "modes/diff-hl/evil-collection-diff-hl" "\
Set up `evil' bindings for `diff-hl'.")
(register-definition-prefixes "modes/diff-hl/evil-collection-diff-hl" '("evil-collection-diff-hl-maps"))


;;; Generated autoloads from modes/diff-mode/evil-collection-diff-mode.el

(autoload 'evil-collection-diff-toggle-setup "modes/diff-mode/evil-collection-diff-mode" "\
Toggle visiting diff buffers in motion state." t)
(autoload 'evil-collection-diff-mode-setup "modes/diff-mode/evil-collection-diff-mode" "\
Set up `evil' bindings for `diff-mode'.")
(register-definition-prefixes "modes/diff-mode/evil-collection-diff-mode" '("evil-collection-diff-"))


;;; Generated autoloads from modes/difftastic/evil-collection-difftastic.el

(autoload 'evil-collection-difftastic-setup "modes/difftastic/evil-collection-difftastic" "\
Set up `evil' bindings for `difftastic'.")
(register-definition-prefixes "modes/difftastic/evil-collection-difftastic" '("evil-collection-difftastic-maps"))


;;; Generated autoloads from modes/dired/evil-collection-dired.el

(autoload 'evil-collection-dired-setup "modes/dired/evil-collection-dired" "\
Set up `evil' bindings for `dired'.")
(register-definition-prefixes "modes/dired/evil-collection-dired" '("evil-collection-dired-maps"))


;;; Generated autoloads from modes/dired-sidebar/evil-collection-dired-sidebar.el

(autoload 'evil-collection-dired-sidebar-setup "modes/dired-sidebar/evil-collection-dired-sidebar" "\
Set up `evil' bindings for `dired-sidebar'.")
(register-definition-prefixes "modes/dired-sidebar/evil-collection-dired-sidebar" '("evil-collection-dired-sidebar-maps"))


;;; Generated autoloads from modes/disk-usage/evil-collection-disk-usage.el

(autoload 'evil-collection-disk-usage-setup "modes/disk-usage/evil-collection-disk-usage" "\
Set up `evil' bindings for `disk-usage'.")
(register-definition-prefixes "modes/disk-usage/evil-collection-disk-usage" '("evil-collection-disk-usage-maps"))


;;; Generated autoloads from modes/distel/evil-collection-distel.el

(autoload 'evil-collection-distel-setup "modes/distel/evil-collection-distel" "\
Set up `evil' bindings for `distel'.")
(register-definition-prefixes "modes/distel/evil-collection-distel" '("evil-collection-distel-maps"))


;;; Generated autoloads from modes/doc-view/evil-collection-doc-view.el

(autoload 'evil-collection-doc-view-setup "modes/doc-view/evil-collection-doc-view" "\
Set up `evil' bindings for `doc-view'.")
(register-definition-prefixes "modes/doc-view/evil-collection-doc-view" '("evil-collection-doc-view-maps"))


;;; Generated autoloads from modes/docker/evil-collection-docker.el

(register-definition-prefixes "modes/docker/evil-collection-docker" '("evil-collection-docker-"))


;;; Generated autoloads from modes/eat/evil-collection-eat.el

(autoload 'evil-collection-eat-setup "modes/eat/evil-collection-eat" "\
Set up `evil' bindings for `eat'.")
(register-definition-prefixes "modes/eat/evil-collection-eat" '("evil-collection-eat-"))


;;; Generated autoloads from modes/ebib/evil-collection-ebib.el

(autoload 'evil-collection-ebib-setup "modes/ebib/evil-collection-ebib" "\
Set up `evil' bindings for `ebib'.")
(register-definition-prefixes "modes/ebib/evil-collection-ebib" '("evil-collection-ebib-maps"))


;;; Generated autoloads from modes/ebuku/evil-collection-ebuku.el

(autoload 'evil-collection-ebuku-setup "modes/ebuku/evil-collection-ebuku" "\
Set up `evil' bindings for `Ebuku'.")


;;; Generated autoloads from modes/edbi/evil-collection-edbi.el

(autoload 'evil-collection-edbi-setup "modes/edbi/evil-collection-edbi" "\
Set up `evil' bindings for EDBI.")
(register-definition-prefixes "modes/edbi/evil-collection-edbi" '("evil-collection-edbi-"))


;;; Generated autoloads from modes/edebug/evil-collection-edebug.el

(autoload 'evil-collection-edebug-setup "modes/edebug/evil-collection-edebug" "\
Set up `evil' bindings for `edebug'.")
(register-definition-prefixes "modes/edebug/evil-collection-edebug" '("evil-collection-edebug-maps"))


;;; Generated autoloads from modes/ediff/evil-collection-ediff.el

(autoload 'evil-collection-ediff-setup "modes/ediff/evil-collection-ediff" "\
Initialize evil-ediff." t)
(register-definition-prefixes "modes/ediff/evil-collection-ediff" '("evil-collection-ediff-"))


;;; Generated autoloads from modes/eglot/evil-collection-eglot.el

(autoload 'evil-collection-eglot-setup "modes/eglot/evil-collection-eglot" "\
Set up `evil' bindings for `eglot'.")
(register-definition-prefixes "modes/eglot/evil-collection-eglot" '("evil-collection-eglot-maps"))


;;; Generated autoloads from modes/eldoc/evil-collection-eldoc.el

(autoload 'evil-collection-eldoc-setup "modes/eldoc/evil-collection-eldoc" "\
Set up `evil' bindings for `eldoc'.")
(register-definition-prefixes "modes/eldoc/evil-collection-eldoc" '("evil-collection-eldoc-"))


;;; Generated autoloads from modes/elfeed/evil-collection-elfeed.el

(autoload 'evil-collection-elfeed-setup "modes/elfeed/evil-collection-elfeed" "\
Set up `evil' bindings for `elfeed'.")
(register-definition-prefixes "modes/elfeed/evil-collection-elfeed" '("evil-collection-elfeed-maps"))


;;; Generated autoloads from modes/elisp-mode/evil-collection-elisp-mode.el

(autoload 'evil-collection-elisp-mode-setup "modes/elisp-mode/evil-collection-elisp-mode" "\
Set up `evil' bindings for `elisp-mode'.")
(register-definition-prefixes "modes/elisp-mode/evil-collection-elisp-mode" '("evil-collection-elisp-mode-"))


;;; Generated autoloads from modes/elisp-refs/evil-collection-elisp-refs.el

(autoload 'evil-collection-elisp-refs-setup "modes/elisp-refs/evil-collection-elisp-refs" "\
Set up `evil' bindings for `elisp-refs'.")
(register-definition-prefixes "modes/elisp-refs/evil-collection-elisp-refs" '("evil-collection-elisp-refs-maps"))


;;; Generated autoloads from modes/elisp-slime-nav/evil-collection-elisp-slime-nav.el

(autoload 'evil-collection-elisp-slime-nav-setup "modes/elisp-slime-nav/evil-collection-elisp-slime-nav" "\
Set up `evil' bindings for `elisp-slime-nav'.")
(register-definition-prefixes "modes/elisp-slime-nav/evil-collection-elisp-slime-nav" '("evil-collection-elisp-slime-nav-maps"))


;;; Generated autoloads from modes/elpaca/evil-collection-elpaca.el

(register-definition-prefixes "modes/elpaca/evil-collection-elpaca" '("evil-collection-elpaca-"))


;;; Generated autoloads from modes/embark/evil-collection-embark.el

(autoload 'evil-collection-embark-setup "modes/embark/evil-collection-embark" "\
Set up `evil' bindings for `embark'.")
(register-definition-prefixes "modes/embark/evil-collection-embark" '("evil-collection-embark-maps"))


;;; Generated autoloads from modes/ement/evil-collection-ement.el

(register-definition-prefixes "modes/ement/evil-collection-ement" '("evil-collection-ement-"))


;;; Generated autoloads from modes/emms/evil-collection-emms.el

(autoload 'evil-collection-emms-browser-setup "modes/emms/evil-collection-emms" "\
Set up `evil' bindings for `emms-browser'.")
(autoload 'evil-collection-emms-playlist-setup "modes/emms/evil-collection-emms" "\
Set up `evil' bindings for `emms-playlist'.")
(autoload 'evil-collection-emms-setup "modes/emms/evil-collection-emms" "\
Set up `evil' bindings for `emms'.")
(register-definition-prefixes "modes/emms/evil-collection-emms" '("evil-collection-emms-"))


;;; Generated autoloads from modes/emoji/evil-collection-emoji.el

(autoload 'evil-collection-emoji-setup "modes/emoji/evil-collection-emoji" "\
Set up `evil' bindings for `emoji'.")
(register-definition-prefixes "modes/emoji/evil-collection-emoji" '("evil-collection-emoji-maps"))


;;; Generated autoloads from modes/epa/evil-collection-epa.el

(autoload 'evil-collection-epa-setup "modes/epa/evil-collection-epa")
(register-definition-prefixes "modes/epa/evil-collection-epa" '("evil-collection-epa-maps"))


;;; Generated autoloads from modes/ert/evil-collection-ert.el

(autoload 'evil-collection-ert-setup "modes/ert/evil-collection-ert" "\
Set up `evil' bindings for `ert'.")
(register-definition-prefixes "modes/ert/evil-collection-ert" '("evil-collection-ert-maps"))


;;; Generated autoloads from modes/eshell/evil-collection-eshell.el

(autoload 'evil-collection-eshell-setup "modes/eshell/evil-collection-eshell" "\
Set up `evil' bindings for `eshell'.")
(register-definition-prefixes "modes/eshell/evil-collection-eshell" '("evil-collection-eshell-"))


;;; Generated autoloads from modes/eval-sexp-fu/evil-collection-eval-sexp-fu.el

(autoload 'evil-collection-eval-sexp-fu-setup "modes/eval-sexp-fu/evil-collection-eval-sexp-fu" "\
Set up `evil' with `eval-sexp-fu'.")
(register-definition-prefixes "modes/eval-sexp-fu/evil-collection-eval-sexp-fu" '("evil-collection-eval-sexp-fu-"))


;;; Generated autoloads from modes/evil-mc/evil-collection-evil-mc.el

(autoload 'evil-collection-evil-mc-setup "modes/evil-mc/evil-collection-evil-mc" "\
Set up `evil' bindings for evil-mc.")
(register-definition-prefixes "modes/evil-mc/evil-collection-evil-mc" '("evil-collection-evil-mc-maps"))


;;; Generated autoloads from modes/eww/evil-collection-eww.el

(autoload 'evil-collection-eww-setup "modes/eww/evil-collection-eww" "\
Set up `evil' bindings for `eww'.")
(register-definition-prefixes "modes/eww/evil-collection-eww" '("evil-collection-eww-maps"))


;;; Generated autoloads from modes/explain-pause-mode/evil-collection-explain-pause-mode.el

(autoload 'evil-collection-explain-pause-mode-setup "modes/explain-pause-mode/evil-collection-explain-pause-mode" "\
Set up `evil' bindings for `explain-pause-mode'.")
(register-definition-prefixes "modes/explain-pause-mode/evil-collection-explain-pause-mode" '("evil-collection-explain-pause-mode-maps"))


;;; Generated autoloads from modes/fanyi/evil-collection-fanyi.el

(autoload 'evil-collection-fanyi-setup "modes/fanyi/evil-collection-fanyi" "\
Set up `evil' bindings for `fanyi'.")
(register-definition-prefixes "modes/fanyi/evil-collection-fanyi" '("evil-collection-fanyi-maps"))


;;; Generated autoloads from modes/finder/evil-collection-finder.el

(autoload 'evil-collection-finder-setup "modes/finder/evil-collection-finder" "\
Set up `evil' bindings for `finder'.")
(register-definition-prefixes "modes/finder/evil-collection-finder" '("evil-collection-finder-maps"))


;;; Generated autoloads from modes/flycheck/evil-collection-flycheck.el

(autoload 'evil-collection-flycheck-setup "modes/flycheck/evil-collection-flycheck" "\
Set up `evil' bindings for `flycheck'.")
(register-definition-prefixes "modes/flycheck/evil-collection-flycheck" '("evil-collection-flycheck-maps"))


;;; Generated autoloads from modes/flymake/evil-collection-flymake.el

(autoload 'evil-collection-flymake-setup "modes/flymake/evil-collection-flymake" "\
Set up `evil' bindings for `flymake'.")
(register-definition-prefixes "modes/flymake/evil-collection-flymake" '("evil-collection-flymake-maps"))


;;; Generated autoloads from modes/forge/evil-collection-forge.el

(autoload 'evil-collection-forge-setup "modes/forge/evil-collection-forge" "\
Set up `evil' bindings for `magit'.")
(register-definition-prefixes "modes/forge/evil-collection-forge" '("evil-collection-forge-"))


;;; Generated autoloads from modes/free-keys/evil-collection-free-keys.el

(autoload 'evil-collection-free-keys-setup "modes/free-keys/evil-collection-free-keys" "\
Set up `evil' bindings for `free-keys'.")
(register-definition-prefixes "modes/free-keys/evil-collection-free-keys" '("evil-collection-free-keys-"))


;;; Generated autoloads from modes/geiser/evil-collection-geiser.el

(autoload 'evil-collection-geiser-setup "modes/geiser/evil-collection-geiser" "\
Set up bindings for `geiser'.")
(register-definition-prefixes "modes/geiser/evil-collection-geiser" '("evil-collection-geiser-"))


;;; Generated autoloads from modes/ggtags/evil-collection-ggtags.el

(autoload 'evil-collection-ggtags-setup "modes/ggtags/evil-collection-ggtags" "\
Set up `evil' bindings for `ggtags'.")
(register-definition-prefixes "modes/ggtags/evil-collection-ggtags" '("evil-collection-ggtags-maps"))


;;; Generated autoloads from modes/git-timemachine/evil-collection-git-timemachine.el

(autoload 'evil-collection-git-timemachine-setup "modes/git-timemachine/evil-collection-git-timemachine" "\
Setup `evil' keybindings for `git-timemachine'.")
(register-definition-prefixes "modes/git-timemachine/evil-collection-git-timemachine" '("evil-collection-git-timemachine-map"))


;;; Generated autoloads from modes/gited/evil-collection-gited.el

(autoload 'evil-collection-gited-setup "modes/gited/evil-collection-gited" "\
Set up `evil' bindings for `gited'.")
(register-definition-prefixes "modes/gited/evil-collection-gited" '("evil-collection-gited-maps"))


;;; Generated autoloads from modes/gnus/evil-collection-gnus.el

(autoload 'evil-collection-gnus-setup "modes/gnus/evil-collection-gnus" "\
Set up `evil' bindings for `gnus'.")
(register-definition-prefixes "modes/gnus/evil-collection-gnus" '("evil-collection-gnus-"))


;;; Generated autoloads from modes/go-mode/evil-collection-go-mode.el

(autoload 'evil-collection-go-mode-setup "modes/go-mode/evil-collection-go-mode" "\
Set up `evil' bindings for `go-mode'.")
(register-definition-prefixes "modes/go-mode/evil-collection-go-mode" '("evil-collection-go-mode-maps"))


;;; Generated autoloads from modes/gptel/evil-collection-gptel.el

(autoload 'evil-collection-gptel-setup "modes/gptel/evil-collection-gptel" "\
Set up `evil' bindings for gptel.")
(register-definition-prefixes "modes/gptel/evil-collection-gptel" '("evil-collection-gptel-"))


;;; Generated autoloads from modes/grep/evil-collection-grep.el

(autoload 'evil-collection-grep-setup "modes/grep/evil-collection-grep" "\
Set up `evil' bindings for `grep'.")
(register-definition-prefixes "modes/grep/evil-collection-grep" '("evil-collection-grep-maps"))


;;; Generated autoloads from modes/guix/evil-collection-guix.el

(autoload 'evil-collection-guix-setup "modes/guix/evil-collection-guix" "\
Set up `evil' bindings for `guix'.")
(register-definition-prefixes "modes/guix/evil-collection-guix" '("evil-collection-guix-"))


;;; Generated autoloads from modes/hackernews/evil-collection-hackernews.el

(autoload 'evil-collection-hackernews-setup "modes/hackernews/evil-collection-hackernews" "\
Set up `evil' bindings for `hackernews-mode'.")
(register-definition-prefixes "modes/hackernews/evil-collection-hackernews" '("evil-collection-hackernews-maps"))


;;; Generated autoloads from modes/helm/evil-collection-helm.el

(autoload 'evil-collection-helm-setup "modes/helm/evil-collection-helm" "\
Set up `evil' bindings for `helm'.")
(register-definition-prefixes "modes/helm/evil-collection-helm" '("evil-collection-helm-"))


;;; Generated autoloads from modes/help/evil-collection-help.el

(autoload 'evil-collection-help-setup "modes/help/evil-collection-help" "\
Set up `evil' bindings for `help'.")
(register-definition-prefixes "modes/help/evil-collection-help" '("evil-collection-help-maps"))


;;; Generated autoloads from modes/helpful/evil-collection-helpful.el

(autoload 'evil-collection-helpful-setup "modes/helpful/evil-collection-helpful" "\
Set up `evil' bindings for `helpful'.")
(register-definition-prefixes "modes/helpful/evil-collection-helpful" '("evil-collection-helpful-maps"))


;;; Generated autoloads from modes/hg-histedit/evil-collection-hg-histedit.el

(autoload 'evil-collection-hg-histedit-setup "modes/hg-histedit/evil-collection-hg-histedit" "\
Set up `evil' bindings for `hg-histedit'.")
(register-definition-prefixes "modes/hg-histedit/evil-collection-hg-histedit" '("evil-collection-hg-histedit-maps"))


;;; Generated autoloads from modes/hideshow/evil-collection-hideshow.el

(autoload 'evil-collection-hideshow-setup "modes/hideshow/evil-collection-hideshow" "\
Set up `evil' bindings for `hideshow'.")
(register-definition-prefixes "modes/hideshow/evil-collection-hideshow" '("evil-collection-hideshow-maps"))


;;; Generated autoloads from modes/hungry-delete/evil-collection-hungry-delete.el

(autoload 'evil-collection-hungry-delete-setup "modes/hungry-delete/evil-collection-hungry-delete" "\
Set up `evil' bindings for `hungry-delete'.")
(register-definition-prefixes "modes/hungry-delete/evil-collection-hungry-delete" '("evil-collection-hungry-delete"))


;;; Generated autoloads from modes/hyrolo/evil-collection-hyrolo.el

(register-definition-prefixes "modes/hyrolo/evil-collection-hyrolo" '("evil-collection-hyrolo-"))


;;; Generated autoloads from modes/ibuffer/evil-collection-ibuffer.el

(autoload 'evil-collection-ibuffer-setup "modes/ibuffer/evil-collection-ibuffer" "\
Set up `evil' bindings for `ibuffer'.")
(register-definition-prefixes "modes/ibuffer/evil-collection-ibuffer" '("evil-collection-ibuffer-maps"))


;;; Generated autoloads from modes/image/evil-collection-image.el

(autoload 'evil-collection-image-setup "modes/image/evil-collection-image" "\
Set up `evil' bindings for `image-mode'.")
(register-definition-prefixes "modes/image/evil-collection-image" '("evil-collection-image-maps"))


;;; Generated autoloads from modes/image+/evil-collection-image+.el

(autoload 'evil-collection-image+-setup "modes/image+/evil-collection-image+" "\
Set up `evil' bindings for `image+'.")
(register-definition-prefixes "modes/image+/evil-collection-image+" '("evil-collection-image+-maps"))


;;; Generated autoloads from modes/image-dired/evil-collection-image-dired.el

(autoload 'evil-collection-image-dired-setup "modes/image-dired/evil-collection-image-dired" "\
Set up `evil' bindings for `image-dired-thumbnail-mode'.")
(register-definition-prefixes "modes/image-dired/evil-collection-image-dired" '("evil-collection-image-dired-maps"))


;;; Generated autoloads from modes/imenu/evil-collection-imenu.el

(autoload 'evil-collection-imenu-setup "modes/imenu/evil-collection-imenu" "\
Set up Evil integration for `imenu'.")


;;; Generated autoloads from modes/imenu-list/evil-collection-imenu-list.el

(autoload 'evil-collection-imenu-list-setup "modes/imenu-list/evil-collection-imenu-list" "\
Set up `evil' bindings for `imenu-list'.")
(register-definition-prefixes "modes/imenu-list/evil-collection-imenu-list" '("evil-collection-imenu-list-maps"))


;;; Generated autoloads from modes/indent/evil-collection-indent.el

(autoload 'evil-collection-indent-setup "modes/indent/evil-collection-indent" "\
Set up `evil' bindings for autoloaded files.")
(register-definition-prefixes "modes/indent/evil-collection-indent" '("evil-collection-indent-maps"))


;;; Generated autoloads from modes/indium/evil-collection-indium.el

(autoload 'evil-collection-indium-setup "modes/indium/evil-collection-indium" "\
Set up `evil' bindings for `indium'.")
(register-definition-prefixes "modes/indium/evil-collection-indium" '("evil-collection-indium-maps"))


;;; Generated autoloads from modes/info/evil-collection-info.el

(autoload 'evil-collection-info-setup "modes/info/evil-collection-info" "\
Set up `evil' bindings for `info-mode'.")
(register-definition-prefixes "modes/info/evil-collection-info" '("evil-collection-info-maps"))


;;; Generated autoloads from modes/ivy/evil-collection-ivy.el

(autoload 'evil-collection-ivy-setup "modes/ivy/evil-collection-ivy" "\
Set up `evil' bindings for `ivy-mode'.")
(register-definition-prefixes "modes/ivy/evil-collection-ivy" '("evil-collection-ivy-maps"))


;;; Generated autoloads from modes/js2-mode/evil-collection-js2-mode.el

(autoload 'evil-collection-js2-mode-setup "modes/js2-mode/evil-collection-js2-mode" "\
Set up `evil' bindings for `js2-mode'.")
(register-definition-prefixes "modes/js2-mode/evil-collection-js2-mode" '("evil-collection-js2-set-evil-shift-width"))


;;; Generated autoloads from modes/kmacro/evil-collection-kmacro.el

(register-definition-prefixes "modes/kmacro/evil-collection-kmacro" '("evil-collection-kmacro-"))


;;; Generated autoloads from modes/kotlin-mode/evil-collection-kotlin-mode.el

(autoload 'evil-collection-kotlin-mode-setup "modes/kotlin-mode/evil-collection-kotlin-mode" "\
Set up `evil' bindings for `kotlin-mode'.")
(register-definition-prefixes "modes/kotlin-mode/evil-collection-kotlin-mode" '("evil-collection-kotlin-maps"))


;;; Generated autoloads from modes/leetcode/evil-collection-leetcode.el

(autoload 'evil-collection-leetcode-setup "modes/leetcode/evil-collection-leetcode" "\
Set up `evil' bindings for `leetcode'.")
(register-definition-prefixes "modes/leetcode/evil-collection-leetcode" '("evil-collection-leetcode-maps"))


;;; Generated autoloads from modes/lispy/evil-collection-lispy.el

(autoload 'evil-collection-lispy-setup "modes/lispy/evil-collection-lispy" "\
Set up `evil' bindings for `lispy'.")
(register-definition-prefixes "modes/lispy/evil-collection-lispy" '("evil-collection-lispy-"))


;;; Generated autoloads from modes/lms/evil-collection-lms.el

(autoload 'evil-collection-lms-setup "modes/lms/evil-collection-lms" "\
Set up `evil' bindings for `lms'.")
(register-definition-prefixes "modes/lms/evil-collection-lms" '("evil-collection-lms-"))


;;; Generated autoloads from modes/log-edit/evil-collection-log-edit.el

(autoload 'evil-collection-log-edit-setup "modes/log-edit/evil-collection-log-edit" "\
Set up `evil' bindings for `log-edit'.")
(register-definition-prefixes "modes/log-edit/evil-collection-log-edit" '("evil-collection-log-edit-maps"))


;;; Generated autoloads from modes/log-view/evil-collection-log-view.el

(autoload 'evil-collection-log-view-setup "modes/log-view/evil-collection-log-view" "\
Set up `evil' bindings for `log-view'.")
(register-definition-prefixes "modes/log-view/evil-collection-log-view" '("evil-collection-log-view-maps"))


;;; Generated autoloads from modes/lsp-ui-imenu/evil-collection-lsp-ui-imenu.el

(autoload 'evil-collection-lsp-ui-imenu-setup "modes/lsp-ui-imenu/evil-collection-lsp-ui-imenu" "\
Set up `evil' bindings for `lsp-ui-imenu'.")
(register-definition-prefixes "modes/lsp-ui-imenu/evil-collection-lsp-ui-imenu" '("evil-collection-lsp-ui-imenu-mode-maps"))


;;; Generated autoloads from modes/lua-mode/evil-collection-lua-mode.el

(autoload 'evil-collection-lua-mode-setup "modes/lua-mode/evil-collection-lua-mode" "\
Set up `evil' bindings for `lua-mode'.")
(register-definition-prefixes "modes/lua-mode/evil-collection-lua-mode" '("evil-collection-lua-mode-"))


;;; Generated autoloads from modes/macrostep/evil-collection-macrostep.el

(autoload 'evil-collection-macrostep-setup "modes/macrostep/evil-collection-macrostep" "\
Set up `evil' bindings for `macrostep'.")
(register-definition-prefixes "modes/macrostep/evil-collection-macrostep" '("evil-collection-macrostep-maps"))


;;; Generated autoloads from modes/magit/evil-collection-magit.el

(autoload 'evil-collection-magit-init "modes/magit/evil-collection-magit" "\
This function completes the setup of evil-collection-magit. It is called
automatically when evil-collection-magit-setup is called.. The only reason to
use this function is if you've called `evil-collection-magit-revert' and wish
to go back to evil-collection-magit behavior." t)
(autoload 'evil-collection-magit-revert "modes/magit/evil-collection-magit" "\
Revert changes by evil-collection-magit that affect default evil+magit behavior." t)
(autoload 'evil-collection-magit-setup "modes/magit/evil-collection-magit" "\
Set up `evil' bindings for `magit'.")
(register-definition-prefixes "modes/magit/evil-collection-magit" '("evil-collection-magit-"))


;;; Generated autoloads from modes/magit-repos/evil-collection-magit-repos.el

(autoload 'evil-collection-magit-repos-setup "modes/magit-repos/evil-collection-magit-repos" "\
Set up `evil' bindings for `magit-repos'.")
(register-definition-prefixes "modes/magit-repos/evil-collection-magit-repos" '("evil-collection-magit-repos-maps"))


;;; Generated autoloads from modes/magit-section/evil-collection-magit-section.el

(register-definition-prefixes "modes/magit-section/evil-collection-magit-section" '("evil-collection-magit-section-"))


;;; Generated autoloads from modes/magit-todos/evil-collection-magit-todos.el

(autoload 'evil-collection-magit-todos-setup "modes/magit-todos/evil-collection-magit-todos" "\
Set up `evil' bindings for `magit-todos'.")
(register-definition-prefixes "modes/magit-todos/evil-collection-magit-todos" '("evil-collection-magit-todos-"))


;;; Generated autoloads from modes/man/evil-collection-man.el

(autoload 'evil-collection-man-setup "modes/man/evil-collection-man" "\
Set up `evil' bindings for `man'.")
(register-definition-prefixes "modes/man/evil-collection-man" '("evil-collection-man-maps"))


;;; Generated autoloads from modes/markdown-mode/evil-collection-markdown-mode.el

(autoload 'evil-collection-markdown-mode-setup "modes/markdown-mode/evil-collection-markdown-mode" "\
Set up `evil' bindings for `markdown-mode'.")
(register-definition-prefixes "modes/markdown-mode/evil-collection-markdown-mode" '("evil-collection-markdown-mode-maps"))


;;; Generated autoloads from modes/minesweeper/evil-collection-minesweeper.el

(autoload 'evil-collection-minesweeper-setup "modes/minesweeper/evil-collection-minesweeper" "\
Set up `evil' bindings for `minesweeper'.")
(register-definition-prefixes "modes/minesweeper/evil-collection-minesweeper" '("evil-collection-minesweeper-maps"))


;;; Generated autoloads from modes/minibuffer/evil-collection-minibuffer.el

(autoload 'evil-collection-minibuffer-setup "modes/minibuffer/evil-collection-minibuffer" "\
Initialize minibuffer for `evil'.")
(register-definition-prefixes "modes/minibuffer/evil-collection-minibuffer" '("evil-collection-minibuffer-"))


;;; Generated autoloads from modes/monky/evil-collection-monky.el

(autoload 'evil-collection-monky-setup "modes/monky/evil-collection-monky" "\
Set up `evil' bindings for `monky'.")
(register-definition-prefixes "modes/monky/evil-collection-monky" '("evil-collection-monky-maps"))


;;; Generated autoloads from modes/mpc/evil-collection-mpc.el

(autoload 'evil-collection-mpc-setup "modes/mpc/evil-collection-mpc" "\
Setup up `evil' bindings for `mpc-mode'.")
(register-definition-prefixes "modes/mpc/evil-collection-mpc" '("evil-collection-mpc-mo"))


;;; Generated autoloads from modes/mpdel/evil-collection-mpdel.el

(autoload 'evil-collection-mpdel-setup "modes/mpdel/evil-collection-mpdel" "\
Set up `evil' bindings for `mpdel'.")
(register-definition-prefixes "modes/mpdel/evil-collection-mpdel" '("evil-collection-mpdel-m"))


;;; Generated autoloads from modes/mpdired/evil-collection-mpdired.el

(autoload 'evil-collection-mpdired-setup "modes/mpdired/evil-collection-mpdired" "\
Set up `evil' bindings for `mpdired'.")
(register-definition-prefixes "modes/mpdired/evil-collection-mpdired" '("evil-collection-mpdired-m"))


;;; Generated autoloads from modes/mu4e/evil-collection-mu4e-1.8.el

(autoload 'evil-collection-mu4e-setup "modes/mu4e/evil-collection-mu4e-1.8" "\
Initialize evil-mu4e if necessary.
If mu4e-main-mode is in evil-state-motion-modes, initialization
is already done earlier.")
(register-definition-prefixes "modes/mu4e/evil-collection-mu4e-1.8" '("evil-collection-mu4e-"))


;;; Generated autoloads from modes/mu4e-conversation/evil-collection-mu4e-conversation.el

(autoload 'evil-collection-mu4e-conversation-setup "modes/mu4e-conversation/evil-collection-mu4e-conversation" "\
Set up `evil' bindings for `mu4e-conversation'.")
(register-definition-prefixes "modes/mu4e-conversation/evil-collection-mu4e-conversation" '("evil-collection-mu4e-conversation-"))


;;; Generated autoloads from modes/neotree/evil-collection-neotree.el

(autoload 'evil-collection-neotree-setup "modes/neotree/evil-collection-neotree" "\
Set up `evil' bindings for `neotree'.")
(register-definition-prefixes "modes/neotree/evil-collection-neotree" '("evil-collection-neotree-maps"))


;;; Generated autoloads from modes/newsticker/evil-collection-newsticker.el

(autoload 'evil-collection-newsticker-setup "modes/newsticker/evil-collection-newsticker" "\
Set up `evil' bindings for `newsticker'.")
(register-definition-prefixes "modes/newsticker/evil-collection-newsticker" '("evil-collection-newsticker-maps"))


;;; Generated autoloads from modes/notmuch/evil-collection-notmuch.el

(autoload 'evil-collection-notmuch-setup "modes/notmuch/evil-collection-notmuch" "\
Set up `evil' bindings for `notmuch'.")
(register-definition-prefixes "modes/notmuch/evil-collection-notmuch" '("evil-collection-notmuch-"))


;;; Generated autoloads from modes/nov/evil-collection-nov.el

(autoload 'evil-collection-nov-setup "modes/nov/evil-collection-nov" "\
Set up `evil' bindings for `nov'.")
(register-definition-prefixes "modes/nov/evil-collection-nov" '("evil-collection-nov-maps"))


;;; Generated autoloads from modes/omnisharp/evil-collection-omnisharp.el

(autoload 'evil-collection-omnisharp-setup "modes/omnisharp/evil-collection-omnisharp" "\
Set up `evil' bindings for `omnisharp'.")
(register-definition-prefixes "modes/omnisharp/evil-collection-omnisharp" '("evil-collection-omnisharp-maps"))


;;; Generated autoloads from modes/org/evil-collection-org.el

(autoload 'evil-collection-org-setup "modes/org/evil-collection-org" "\
Set up `evil' bindings for `org'.")
(register-definition-prefixes "modes/org/evil-collection-org" '("evil-collection-org-maps"))


;;; Generated autoloads from modes/org-present/evil-collection-org-present.el

(autoload 'evil-collection-org-present-setup "modes/org-present/evil-collection-org-present" "\
Set up `evil' bindings for `org-present'.")
(register-definition-prefixes "modes/org-present/evil-collection-org-present" '("evil-collection-org-present-maps"))


;;; Generated autoloads from modes/org-roam/evil-collection-org-roam.el

(register-definition-prefixes "modes/org-roam/evil-collection-org-roam" '("evil-collection-org-roam-"))


;;; Generated autoloads from modes/osx-dictionary/evil-collection-osx-dictionary.el

(autoload 'evil-collection-osx-dictionary-setup "modes/osx-dictionary/evil-collection-osx-dictionary" "\
Set up `evil' bindings for `osx-dictionary'.")
(register-definition-prefixes "modes/osx-dictionary/evil-collection-osx-dictionary" '("evil-collection-osx-dictionary-maps"))


;;; Generated autoloads from modes/outline/evil-collection-outline.el

(autoload 'evil-collection-outline-setup "modes/outline/evil-collection-outline" "\
Set up `evil' bindings for `outline'.")
(register-definition-prefixes "modes/outline/evil-collection-outline" '("evil-collection-outline-"))


;;; Generated autoloads from modes/ovpn-mode/evil-collection-ovpn-mode.el

(autoload 'evil-collection-ovpn-mode-setup "modes/ovpn-mode/evil-collection-ovpn-mode" "\
Set up `evil' bindings for `ovpn-mode'.")
(register-definition-prefixes "modes/ovpn-mode/evil-collection-ovpn-mode" '("evil-collection-ovpn-mode-maps"))


;;; Generated autoloads from modes/p-search/evil-collection-p-search.el

(register-definition-prefixes "modes/p-search/evil-collection-p-search" '("evil-collection-p-search-"))


;;; Generated autoloads from modes/p4/evil-collection-p4.el

(autoload 'evil-collection-p4-setup "modes/p4/evil-collection-p4" "\
Set up `evil' bindings for `p4'.")
(register-definition-prefixes "modes/p4/evil-collection-p4" '("evil-collection-p4-maps"))


;;; Generated autoloads from modes/package-menu/evil-collection-package-menu.el

(autoload 'evil-collection-package-menu-setup "modes/package-menu/evil-collection-package-menu" "\
Set up `evil' bindings for `package-menu'.")
(register-definition-prefixes "modes/package-menu/evil-collection-package-menu" '("evil-collection-package-menu-maps"))


;;; Generated autoloads from modes/pass/evil-collection-pass.el

(autoload 'evil-collection-pass-setup "modes/pass/evil-collection-pass" "\
Set up `evil' bindings for `pass-mode'.")
(register-definition-prefixes "modes/pass/evil-collection-pass" '("evil-collection-pass-"))


;;; Generated autoloads from modes/pdf/evil-collection-pdf.el

(autoload 'evil-collection-pdf-setup "modes/pdf/evil-collection-pdf" "\
Set up `evil' bindings for `pdf-view'.")
(register-definition-prefixes "modes/pdf/evil-collection-pdf" '("evil-collection-pdf-"))


;;; Generated autoloads from modes/popup/evil-collection-popup.el

(autoload 'evil-collection-popup-setup "modes/popup/evil-collection-popup" "\
Set up `evil' bindings for `popup'.")
(register-definition-prefixes "modes/popup/evil-collection-popup" '("evil-collection-popup-maps"))


;;; Generated autoloads from modes/proced/evil-collection-proced.el

(autoload 'evil-collection-proced-setup "modes/proced/evil-collection-proced" "\
Set up `evil' bindings for `proced'.")
(register-definition-prefixes "modes/proced/evil-collection-proced" '("evil-collection-proced-maps"))


;;; Generated autoloads from modes/process-menu/evil-collection-process-menu.el

(autoload 'evil-collection-process-menu-setup "modes/process-menu/evil-collection-process-menu" "\
Set up `evil' bindings for `list-processes'.")
(register-definition-prefixes "modes/process-menu/evil-collection-process-menu" '("evil-collection-process-menu-maps"))


;;; Generated autoloads from modes/prodigy/evil-collection-prodigy.el

(autoload 'evil-collection-prodigy-setup "modes/prodigy/evil-collection-prodigy" "\
Set up `evil' bindings for `prodigy'.")
(register-definition-prefixes "modes/prodigy/evil-collection-prodigy" '("evil-collection-prodigy-maps"))


;;; Generated autoloads from modes/profiler/evil-collection-profiler.el

(autoload 'evil-collection-profiler-setup "modes/profiler/evil-collection-profiler" "\
Set up `evil' bindings for `profiler'.")
(register-definition-prefixes "modes/profiler/evil-collection-profiler" '("evil-collection-profiler-maps"))


;;; Generated autoloads from modes/python/evil-collection-python.el

(autoload 'evil-collection-python-setup "modes/python/evil-collection-python" "\
Set up `evil' bindings for `python'.")
(register-definition-prefixes "modes/python/evil-collection-python" '("evil-collection-python-"))


;;; Generated autoloads from modes/quickrun/evil-collection-quickrun.el

(autoload 'evil-collection-quickrun-setup "modes/quickrun/evil-collection-quickrun" "\
Set up `evil' bindings for `quickrun'..")
(register-definition-prefixes "modes/quickrun/evil-collection-quickrun" '("evil-collection-quickrun-maps"))


;;; Generated autoloads from modes/racer/evil-collection-racer.el

(autoload 'evil-collection-racer-setup "modes/racer/evil-collection-racer" "\
Set up `evil' bindings for `racer'.")
(register-definition-prefixes "modes/racer/evil-collection-racer" '("evil-collection-racer-maps"))


;;; Generated autoloads from modes/racket-describe/evil-collection-racket-describe.el

(autoload 'evil-collection-racket-describe-setup "modes/racket-describe/evil-collection-racket-describe" "\
Set up `evil' bindings for `racket-describe'.")
(register-definition-prefixes "modes/racket-describe/evil-collection-racket-describe" '("evil-collection-racket-describe-maps"))


;;; Generated autoloads from modes/reader/evil-collection-reader.el

(autoload 'evil-collection-reader-setup "modes/reader/evil-collection-reader" "\
Set up `evil' bindings for `reader'.")
(register-definition-prefixes "modes/reader/evil-collection-reader" '("evil-collection-reader-"))


;;; Generated autoloads from modes/realgud/evil-collection-realgud.el

(autoload 'evil-collection-realgud-setup "modes/realgud/evil-collection-realgud" "\
Set up `evil' bindings for `realgud'.")
(register-definition-prefixes "modes/realgud/evil-collection-realgud" '("evil-collection-realgud-maps"))


;;; Generated autoloads from modes/reftex/evil-collection-reftex.el

(autoload 'evil-collection-reftex-setup "modes/reftex/evil-collection-reftex" "\
Set up `evil' bindings for `reftex'.")
(register-definition-prefixes "modes/reftex/evil-collection-reftex" '("evil-collection-reftex-maps"))


;;; Generated autoloads from modes/replace/evil-collection-replace.el

(autoload 'evil-collection-replace-setup "modes/replace/evil-collection-replace" "\
Set up `evil' bindings for `occur'.")
(register-definition-prefixes "modes/replace/evil-collection-replace" '("evil-collection-replace-maps"))


;;; Generated autoloads from modes/restclient/evil-collection-restclient.el

(autoload 'evil-collection-restclient-setup "modes/restclient/evil-collection-restclient" "\
Set up `evil' bindings for `restclient'.")
(register-definition-prefixes "modes/restclient/evil-collection-restclient" '("evil-collection-restclient-"))


;;; Generated autoloads from modes/rg/evil-collection-rg.el

(autoload 'evil-collection-rg-setup "modes/rg/evil-collection-rg" "\
Set up `evil' bindings for `rg'.")
(register-definition-prefixes "modes/rg/evil-collection-rg" '("evil-collection-rg-maps"))


;;; Generated autoloads from modes/ripgrep/evil-collection-ripgrep.el

(autoload 'evil-collection-ripgrep-setup "modes/ripgrep/evil-collection-ripgrep" "\
Set up `evil' bindings for `ripgrep'.")
(register-definition-prefixes "modes/ripgrep/evil-collection-ripgrep" '("evil-collection-ripgrep-maps"))


;;; Generated autoloads from modes/rjsx-mode/evil-collection-rjsx-mode.el

(autoload 'evil-collection-rjsx-mode-setup "modes/rjsx-mode/evil-collection-rjsx-mode" "\
Set up `evil' bindings for `rjsx-mode'.")
(register-definition-prefixes "modes/rjsx-mode/evil-collection-rjsx-mode" '("evil-collection-rjsx-maps"))


;;; Generated autoloads from modes/robe/evil-collection-robe.el

(autoload 'evil-collection-robe-setup "modes/robe/evil-collection-robe" "\
Set up `evil' bindings for `robe'.")
(register-definition-prefixes "modes/robe/evil-collection-robe" '("evil-collection-robe-maps"))


;;; Generated autoloads from modes/rtags/evil-collection-rtags.el

(autoload 'evil-collection-rtags-setup "modes/rtags/evil-collection-rtags" "\
Set up `evil' bindings for `rtags'.")
(register-definition-prefixes "modes/rtags/evil-collection-rtags" '("evil-collection-rtags-maps"))


;;; Generated autoloads from modes/ruby-mode/evil-collection-ruby-mode.el

(autoload 'evil-collection-ruby-mode-setup "modes/ruby-mode/evil-collection-ruby-mode" "\
Set up `evil' bindings for `ruby'.")
(register-definition-prefixes "modes/ruby-mode/evil-collection-ruby-mode" '("evil-collection-ruby-mode-"))


;;; Generated autoloads from modes/scheme/evil-collection-scheme.el

(autoload 'evil-collection-scheme-setup "modes/scheme/evil-collection-scheme" "\
Set up `evil' bindings for `scheme'.")
(register-definition-prefixes "modes/scheme/evil-collection-scheme" '("evil-collection-scheme-"))


;;; Generated autoloads from modes/scroll-lock/evil-collection-scroll-lock.el

(autoload 'evil-collection-scroll-lock-setup "modes/scroll-lock/evil-collection-scroll-lock" "\
Set up `evil' bindings for `scroll-lock'.")
(register-definition-prefixes "modes/scroll-lock/evil-collection-scroll-lock" '("evil-collection-scroll-lock-maps"))


;;; Generated autoloads from modes/selectrum/evil-collection-selectrum.el

(autoload 'evil-collection-selectrum-setup "modes/selectrum/evil-collection-selectrum" "\
Set up `evil' bindings for `selectrum-mode'.")
(register-definition-prefixes "modes/selectrum/evil-collection-selectrum" '("evil-collection-selectrum-maps"))


;;; Generated autoloads from modes/sh-script/evil-collection-sh-script.el

(autoload 'evil-collection-sh-script-setup "modes/sh-script/evil-collection-sh-script" "\
Set up `evil' bindings for `sh-script'.")
(register-definition-prefixes "modes/sh-script/evil-collection-sh-script" '("evil-collection-sh-script-"))


;;; Generated autoloads from modes/shortdoc/evil-collection-shortdoc.el

(autoload 'evil-collection-shortdoc-setup "modes/shortdoc/evil-collection-shortdoc" "\
Set up `evil' bindings for `shortdoc'.")
(register-definition-prefixes "modes/shortdoc/evil-collection-shortdoc" '("evil-collection-shortdoc-maps"))


;;; Generated autoloads from modes/simple/evil-collection-simple.el

(autoload 'evil-collection-simple-setup "modes/simple/evil-collection-simple" "\
Set up `evil' bindings for `simple'.")
(register-definition-prefixes "modes/simple/evil-collection-simple" '("evil-collection-simple-maps"))


;;; Generated autoloads from modes/simple-mpc/evil-collection-simple-mpc.el

(autoload 'evil-collection-simple-mpc-setup "modes/simple-mpc/evil-collection-simple-mpc" "\
Set up simple-mpc bindings and main view.")
(register-definition-prefixes "modes/simple-mpc/evil-collection-simple-mpc" '("evil-collection-simple-mpc-" "simple-mpc-main-buffer-name"))


;;; Generated autoloads from modes/slime/evil-collection-slime.el

(autoload 'evil-collection-slime-setup "modes/slime/evil-collection-slime" "\
Set up `evil' bindings for `slime'.")
(register-definition-prefixes "modes/slime/evil-collection-slime" '("evil-collection-slime-"))


;;; Generated autoloads from modes/sly/evil-collection-sly.el

(autoload 'evil-collection-sly-setup "modes/sly/evil-collection-sly" "\
Set up `evil' bindings for `sly'.")
(register-definition-prefixes "modes/sly/evil-collection-sly" '("evil-collection-sly-"))


;;; Generated autoloads from modes/smerge-mode/evil-collection-smerge-mode.el

(autoload 'evil-collection-smerge-mode-setup "modes/smerge-mode/evil-collection-smerge-mode" "\
Setup up `evil' bindings for `smerge-mode'.")
(register-definition-prefixes "modes/smerge-mode/evil-collection-smerge-mode" '("evil-collection-smerge-mode-maps"))


;;; Generated autoloads from modes/snake/evil-collection-snake.el

(autoload 'evil-collection-snake-setup "modes/snake/evil-collection-snake" "\
Set up `evil' bindings for `snake'.")
(register-definition-prefixes "modes/snake/evil-collection-snake" '("evil-collection-snake-maps"))


;;; Generated autoloads from modes/so-long/evil-collection-so-long.el

(register-definition-prefixes "modes/so-long/evil-collection-so-long" '("evil-collection-so-long-"))


;;; Generated autoloads from modes/speedbar/evil-collection-speedbar.el

(autoload 'evil-collection-speedbar-setup "modes/speedbar/evil-collection-speedbar" "\
Set up `evil' bindings for `speedbar'.")
(register-definition-prefixes "modes/speedbar/evil-collection-speedbar" '("evil-collection-speedbar-"))


;;; Generated autoloads from modes/tab-bar/evil-collection-tab-bar.el

(register-definition-prefixes "modes/tab-bar/evil-collection-tab-bar" '("evil-collection-tab-bar-"))


;;; Generated autoloads from modes/tablist/evil-collection-tablist.el

(autoload 'evil-collection-tablist-setup "modes/tablist/evil-collection-tablist" "\
Set up `evil' bindings for `tablist'.")
(register-definition-prefixes "modes/tablist/evil-collection-tablist" '("evil-collection-tablist-maps"))


;;; Generated autoloads from modes/tabulated-list/evil-collection-tabulated-list.el

(autoload 'evil-collection-tabulated-list-setup "modes/tabulated-list/evil-collection-tabulated-list" "\
Set up `evil' bindings for `tabulated-list'.")
(register-definition-prefixes "modes/tabulated-list/evil-collection-tabulated-list" '("evil-collection-tabulated-list-maps"))


;;; Generated autoloads from modes/tar-mode/evil-collection-tar-mode.el

(autoload 'evil-collection-tar-mode-setup "modes/tar-mode/evil-collection-tar-mode" "\
Set up `evil' bindings for `tar-mode'.")
(register-definition-prefixes "modes/tar-mode/evil-collection-tar-mode" '("evil-collection-tar-mode-maps"))


;;; Generated autoloads from modes/telega/evil-collection-telega.el

(autoload 'evil-collection-telega-setup "modes/telega/evil-collection-telega" "\
Set up `evil' bindings for `telega'.")
(register-definition-prefixes "modes/telega/evil-collection-telega" '("evil-collection-telega-m"))


;;; Generated autoloads from modes/term/evil-collection-term.el

(autoload 'evil-collection-term-setup "modes/term/evil-collection-term" "\
Set up `evil' bindings for `term'.")
(register-definition-prefixes "modes/term/evil-collection-term" '("evil-collection-term-"))


;;; Generated autoloads from modes/tetris/evil-collection-tetris.el

(autoload 'evil-collection-tetris-setup "modes/tetris/evil-collection-tetris" "\
Set up `evil' bindings for `tetris'.")
(register-definition-prefixes "modes/tetris/evil-collection-tetris" '("evil-collection-tetris-maps"))


;;; Generated autoloads from modes/thread/evil-collection-thread.el

(autoload 'evil-collection-thread-setup "modes/thread/evil-collection-thread" "\
Set up `evil' bindings for `thread'.")
(register-definition-prefixes "modes/thread/evil-collection-thread" '("evil-collection-thread-maps"))


;;; Generated autoloads from modes/tide/evil-collection-tide.el

(autoload 'evil-collection-tide-setup "modes/tide/evil-collection-tide" "\
Set up `evil' bindings for `tide'.")
(register-definition-prefixes "modes/tide/evil-collection-tide" '("evil-collection-tide-maps"))


;;; Generated autoloads from modes/timer-list/evil-collection-timer-list.el

(autoload 'evil-collection-timer-list-setup "modes/timer-list/evil-collection-timer-list" "\
Set up `evil' bindings for `timer-list'.")
(register-definition-prefixes "modes/timer-list/evil-collection-timer-list" '("evil-collection-timer-list-maps"))


;;; Generated autoloads from modes/transmission/evil-collection-transmission.el

(autoload 'evil-collection-transmission-setup "modes/transmission/evil-collection-transmission" "\
Set up `evil' bindings for `transmission'.")
(register-definition-prefixes "modes/transmission/evil-collection-transmission" '("evil-collection-transmission-maps"))


;;; Generated autoloads from modes/trashed/evil-collection-trashed.el

(autoload 'evil-collection-trashed-setup "modes/trashed/evil-collection-trashed" "\
Set up `evil' bindings for `trashed'.")
(register-definition-prefixes "modes/trashed/evil-collection-trashed" '("evil-collection-trashed-maps"))


;;; Generated autoloads from modes/tuareg/evil-collection-tuareg.el

(autoload 'evil-collection-tuareg-setup "modes/tuareg/evil-collection-tuareg" "\
Set up `evil' bindings for `tuareg'.")
(register-definition-prefixes "modes/tuareg/evil-collection-tuareg" '("evil-collection-tuareg-maps"))


;;; Generated autoloads from modes/typescript-mode/evil-collection-typescript-mode.el

(autoload 'evil-collection-typescript-mode-setup "modes/typescript-mode/evil-collection-typescript-mode" "\
Set up `evil' bindings for `typescript-mode'.")
(register-definition-prefixes "modes/typescript-mode/evil-collection-typescript-mode" '("evil-collection-typescript-mode-set-evil-shift-width"))


;;; Generated autoloads from modes/ultra-scroll/evil-collection-ultra-scroll.el

(register-definition-prefixes "modes/ultra-scroll/evil-collection-ultra-scroll" '("evil-collection-ultra-scroll-"))


;;; Generated autoloads from modes/unimpaired/evil-collection-unimpaired.el

(put 'global-evil-collection-unimpaired-mode 'globalized-minor-mode t)
(defvar global-evil-collection-unimpaired-mode nil "\
Non-nil if Global Evil-Collection-Unimpaired mode is enabled.
See the `global-evil-collection-unimpaired-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-evil-collection-unimpaired-mode'.")
(custom-autoload 'global-evil-collection-unimpaired-mode "modes/unimpaired/evil-collection-unimpaired" nil)
(autoload 'global-evil-collection-unimpaired-mode "modes/unimpaired/evil-collection-unimpaired" "\
Toggle Evil-Collection-Unimpaired mode in all buffers.
With prefix ARG, enable Global Evil-Collection-Unimpaired mode if ARG
is positive; otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Evil-Collection-Unimpaired mode is enabled in all buffers where
`evil-collection-unimpaired-mode-on' would do it.

See `evil-collection-unimpaired-mode' for more information on
Evil-Collection-Unimpaired mode.

(fn &optional ARG)" t)
(autoload 'evil-collection-unimpaired-setup "modes/unimpaired/evil-collection-unimpaired" "\
Set up unimpaired-like bindings.")
(register-definition-prefixes "modes/unimpaired/evil-collection-unimpaired" '("evil-collection-unimpaired-"))


;;; Generated autoloads from modes/vc-annotate/evil-collection-vc-annotate.el

(autoload 'evil-collection-vc-annotate-setup "modes/vc-annotate/evil-collection-vc-annotate" "\
Set up `evil' bindings for `vc-annotate'.")
(register-definition-prefixes "modes/vc-annotate/evil-collection-vc-annotate" '("evil-collection-vc-annotate-maps"))


;;; Generated autoloads from modes/vc-dir/evil-collection-vc-dir.el

(autoload 'evil-collection-vc-dir-setup "modes/vc-dir/evil-collection-vc-dir" "\
Set up `evil' bindings for `vc-dir'.")
(register-definition-prefixes "modes/vc-dir/evil-collection-vc-dir" '("evil-collection-vc-dir-maps"))


;;; Generated autoloads from modes/vc-git/evil-collection-vc-git.el

(autoload 'evil-collection-vc-git-setup "modes/vc-git/evil-collection-vc-git" "\
Set up `evil' bindings for `vc-git'.")
(register-definition-prefixes "modes/vc-git/evil-collection-vc-git" '("evil-collection-vc-git-maps"))


;;; Generated autoloads from modes/vdiff/evil-collection-vdiff.el

(autoload 'evil-collection-vdiff-setup "modes/vdiff/evil-collection-vdiff" "\
Set up `evil' bindings for `vdiff-mode'.")
(register-definition-prefixes "modes/vdiff/evil-collection-vdiff" '("evil-collection-vdiff-maps"))


;;; Generated autoloads from modes/vertico/evil-collection-vertico.el

(autoload 'evil-collection-vertico-setup "modes/vertico/evil-collection-vertico" "\
Set up `evil' bindings for `vertico'.")
(register-definition-prefixes "modes/vertico/evil-collection-vertico" '("evil-collection-vertico-want-want-C-u-in-insert"))


;;; Generated autoloads from modes/view/evil-collection-view.el

(autoload 'evil-collection-view-setup "modes/view/evil-collection-view" "\
Set up `evil' bindings for `view'.")
(register-definition-prefixes "modes/view/evil-collection-view" '("evil-collection-view-maps"))


;;; Generated autoloads from modes/vlf/evil-collection-vlf.el

(autoload 'evil-collection-vlf-setup "modes/vlf/evil-collection-vlf" "\
Set up `evil' bindings for `vlf'.")
(register-definition-prefixes "modes/vlf/evil-collection-vlf" '("evil-collection-vlf-"))


;;; Generated autoloads from modes/vterm/evil-collection-vterm.el

(autoload 'evil-collection-vterm-setup "modes/vterm/evil-collection-vterm" "\
Set up `evil' bindings for `vterm'.")
(register-definition-prefixes "modes/vterm/evil-collection-vterm" '("evil-collection-vterm-"))


;;; Generated autoloads from modes/vundo/evil-collection-vundo.el

(autoload 'evil-collection-vundo-setup "modes/vundo/evil-collection-vundo" "\
Set up `evil' bindings for `vundo'.")
(register-definition-prefixes "modes/vundo/evil-collection-vundo" '("evil-collection-vundo-"))


;;; Generated autoloads from modes/w3m/evil-collection-w3m.el

(autoload 'evil-collection-w3m-setup "modes/w3m/evil-collection-w3m" "\
Set up `evil' bindings for `w3m'.")
(register-definition-prefixes "modes/w3m/evil-collection-w3m" '("evil-collection-w3m-maps"))


;;; Generated autoloads from modes/wdired/evil-collection-wdired.el

(autoload 'evil-collection-wdired-setup "modes/wdired/evil-collection-wdired" "\
Set up `evil' bindings for `wdired'.")
(register-definition-prefixes "modes/wdired/evil-collection-wdired" '("evil-collection-wdired-maps"))


;;; Generated autoloads from modes/wgrep/evil-collection-wgrep.el

(autoload 'evil-collection-wgrep-setup "modes/wgrep/evil-collection-wgrep" "\
Set up `evil' bindings for `wgrep'.")
(register-definition-prefixes "modes/wgrep/evil-collection-wgrep" '("evil-collection-wgrep-maps"))


;;; Generated autoloads from modes/which-key/evil-collection-which-key.el

(autoload 'evil-collection-which-key-setup "modes/which-key/evil-collection-which-key" "\
Set up `evil' bindings for `which-key'.")
(register-definition-prefixes "modes/which-key/evil-collection-which-key" '("evil-collection-which-key-maps"))


;;; Generated autoloads from modes/with-editor/evil-collection-with-editor.el

(autoload 'evil-collection-with-editor-setup "modes/with-editor/evil-collection-with-editor" "\
Set up `evil' bindings for `with-editor'.")
(register-definition-prefixes "modes/with-editor/evil-collection-with-editor" '("evil-collection-with-editor-maps"))


;;; Generated autoloads from modes/woman/evil-collection-woman.el

(autoload 'evil-collection-woman-setup "modes/woman/evil-collection-woman" "\
Set up `evil' bindings for `woman'.")
(register-definition-prefixes "modes/woman/evil-collection-woman" '("evil-collection-woman-maps"))


;;; Generated autoloads from modes/xref/evil-collection-xref.el

(autoload 'evil-collection-xref-setup "modes/xref/evil-collection-xref" "\
Set up `evil' bindings for `xref'.")
(register-definition-prefixes "modes/xref/evil-collection-xref" '("evil-collection-xref-maps"))


;;; Generated autoloads from modes/xwidget/evil-collection-xwidget.el

(autoload 'evil-collection-xwidget-setup "modes/xwidget/evil-collection-xwidget" "\
Set up `evil' bindings for `xwidget'.")
(register-definition-prefixes "modes/xwidget/evil-collection-xwidget" '("evil-collection-xwidget-"))


;;; Generated autoloads from modes/yaml-mode/evil-collection-yaml-mode.el

(autoload 'evil-collection-yaml-mode-setup "modes/yaml-mode/evil-collection-yaml-mode" "\
Set up `evil' bindings for `yaml'.")
(register-definition-prefixes "modes/yaml-mode/evil-collection-yaml-mode" '("evil-collection-yaml-mode-"))


;;; Generated autoloads from modes/youtube-dl/evil-collection-youtube-dl.el

(autoload 'evil-collection-youtube-dl-setup "modes/youtube-dl/evil-collection-youtube-dl" "\
Set up `evil' bindings for `youtube-dl'.")
(register-definition-prefixes "modes/youtube-dl/evil-collection-youtube-dl" '("evil-collection-youtube-dl-maps"))


;;; Generated autoloads from modes/zmusic/evil-collection-zmusic.el

(autoload 'evil-collection-zmusic-setup "modes/zmusic/evil-collection-zmusic" "\
Set up `evil' bindings for `zmusic'.")
(register-definition-prefixes "modes/zmusic/evil-collection-zmusic" '("evil-collection-zmusic-maps"))


;;; Generated autoloads from modes/ztree/evil-collection-ztree.el

(autoload 'evil-collection-ztree-setup "modes/ztree/evil-collection-ztree" "\
Set up `evil' bindings for `ztree'.")
(register-definition-prefixes "modes/ztree/evil-collection-ztree" '("evil-collection-ztree-maps"))

;;; End of scraped data

(provide 'evil-collection-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-collection-autoloads.el ends here
